// Explicit browser assets. Never publish the workspace root.
export const PUBLIC_FILES = Object.freeze([
  'index.html',
  'styles.css',
  'src/app.js',
  'src/theory.js',
  'src/library.js',
  'src/storage.js',
  'src/learning.js',
  'src/transport.js',
  'src/samples.js',
  ...[
    'rhythm',
    'voicings',
    'songs',
    'audio-engine',
    'exports',
    'practice',
    'studio',
    'arrangement',
    'fret-path',
    'revision',
    'tunings',
  ].map((n) => `src/${n}.js`),
  'assets/fonts/Manrope.ttf',
  'assets/fonts/OFL.txt',
  'assets/guitar/D5.mp3',
  ...['E2', 'A2', 'C3', 'Ds3', 'Fs3', 'A3', 'C4', 'Ds4', 'Fs4', 'A4', 'C5', 'Ds5', 'Fs5', 'A5', 'C6'].map(
    (n) => `assets/electric/${n}.mp3`,
  ),
  ...['E2', 'A2', 'C3', 'E3', 'A3', 'C4', 'E4', 'A4', 'C5'].map((n) => `assets/guitar/${n}.mp3`),
]);
