import { PUBLIC_FILES } from './public-files.mjs';
export const LICENSE_FILES = [
  'assets/guitar/LICENSE.md',
  'assets/guitar/sample-source-info.txt',
  'assets/electric/LICENSE.md',
  'assets/electric/sample-source-info.txt',
];
export const BROWSER_FILES = [...PUBLIC_FILES, ...LICENSE_FILES];
export const SOURCE_FILES = [
  ...new Set([
    ...BROWSER_FILES,
    'assets/v6-manifest.json',
    'src/synth.js',
    'README.md',
    'SECURITY.md',
    'GITHUB_RELEASE_CHECKLIST.md',
    '.gitignore',
    'package.json',
    'docs/guitar-lesson-studio.png',
    'Start Guitar Studio.cmd',
    'Start Guitar Lesson Studio.cmd',
    ...[
      'server',
      'launch',
      'public-files',
      'release-files',
      'build-release',
      'audit-release',
      'verify-http',
      'verify-browser',
      'verify-studio',
      'verify-v6',
      'verify-v6-features',
      'verify-v7',
      'verify-v8',
      'hash-assets',
    ].map((n) => `scripts/${n}.mjs`),
    ...[
      'audio',
      'learning',
      'library',
      'revision',
      'samples',
      'storage',
      'studio-core',
      'synth',
      'theory',
      'transport',
      'tunings',
    ].map((n) => `tests/${n}.test.mjs`),
  ]),
];
