/**
 * Small, dependency-free starter library for the Guitar prototype.
 *
 * `shape` is always low E -> high e. Numbers are fret offsets from the nut
 * (or from the capo when one is active); `x` means that string is muted.
 * Open strings are represented by 0.
 */
const shape = (values) => {
  if (!Array.isArray(values) || values.length !== 6) {
    throw new Error('Every guitar shape must contain six string values.');
  }
  if (values.some((value) => value !== 'x' && (!Number.isInteger(value) || value < 0))) {
    throw new Error('Shape frets must be x or non-negative integers.');
  }
  return Object.freeze([...values]);
};
const entry = (id, title, category, frets, root, learningNote, extra = {}) =>
  Object.freeze({ id, title, category, shape: shape(frets), root, learningNote, ...extra });
export const guitarLibrary = Object.freeze([
  entry(
    'open-c',
    'C major',
    'Open chords',
    ['x', 3, 2, 0, 1, 0],
    'C',
    'Keep the low E muted; this is the familiar open C shape.',
  ),
  entry(
    'open-a',
    'A major',
    'Open chords',
    ['x', 0, 2, 2, 2, 0],
    'A',
    'Use one finger across the three middle notes if that is comfortable.',
  ),
  entry(
    'open-g',
    'G major',
    'Open chords',
    [3, 2, 0, 0, 0, 3],
    'G',
    'The low and high G roots make this a useful full-sounding beginner shape.',
  ),
  entry(
    'open-e',
    'E major',
    'Open chords',
    [0, 2, 2, 1, 0, 0],
    'E',
    'All six strings ring; notice the open E roots on strings six and one.',
  ),
  entry(
    'open-d',
    'D major',
    'Open chords',
    ['x', 'x', 0, 2, 3, 2],
    'D',
    'Start at the open D string and keep the two lowest strings muted.',
  ),
  entry(
    'open-em',
    'E minor',
    'Open chords',
    [0, 2, 2, 0, 0, 0],
    'E',
    'Compare this open shape with E major: only the third changes.',
  ),
  entry(
    'open-am',
    'A minor',
    'Open chords',
    ['x', 0, 2, 2, 1, 0],
    'A',
    'A minor is the A shape with a lowered third on the B string.',
  ),
  entry(
    'open-dm',
    'D minor',
    'Open chords',
    ['x', 'x', 0, 2, 3, 1],
    'D',
    'The first-fret high E gives the minor color.',
  ),
  entry(
    'open-f',
    'F major · small',
    'Open chords',
    ['x', 'x', 3, 2, 1, 1],
    'F',
    'A four-string F: use a small barre across the two highest strings.',
  ),
  entry(
    'open-g-four',
    'G major · four fingers',
    'Open chords',
    [3, 2, 0, 0, 3, 3],
    'G',
    'Keep the top two fingers in place when moving to Cadd9.',
  ),
  entry('open-c-g', 'C/G', 'Open chords', [3, 3, 2, 0, 1, 0], 'C', 'Open C with G in the bass.'),
  entry(
    'open-d-fsharp',
    'D/F#',
    'Open chords',
    [2, 'x', 0, 2, 3, 2],
    'D',
    'D major with its third, F#, in the bass.',
  ),
  entry(
    'open-a7',
    'A7',
    'Sevenths & color',
    ['x', 0, 2, 0, 2, 0],
    'A',
    'Lift the G-string finger from A major to add the minor seventh.',
  ),
  entry(
    'open-b7',
    'B7',
    'Sevenths & color',
    ['x', 2, 1, 2, 0, 2],
    'B',
    'A familiar dominant chord in the key of E.',
  ),
  entry(
    'open-c7',
    'C7',
    'Sevenths & color',
    ['x', 3, 2, 3, 1, 0],
    'C',
    'Add Bb on the G string to the open C shape.',
  ),
  entry(
    'open-d7',
    'D7',
    'Sevenths & color',
    ['x', 'x', 0, 2, 1, 2],
    'D',
    'The C on the B string supplies the minor seventh.',
  ),
  entry(
    'open-e7',
    'E7',
    'Sevenths & color',
    [0, 2, 0, 1, 0, 0],
    'E',
    'Open D supplies the seventh; all six strings sound.',
  ),
  entry(
    'open-g7',
    'G7',
    'Sevenths & color',
    [3, 2, 0, 0, 0, 1],
    'G',
    'The high F pulls naturally toward a C chord.',
  ),
  entry('open-am7', 'Am7', 'Sevenths & color', ['x', 0, 2, 0, 1, 0], 'A', 'A soft open minor seventh.'),
  entry('open-em7', 'Em7', 'Sevenths & color', [0, 2, 0, 0, 0, 0], 'E', 'A one-finger minor seventh shape.'),
  entry(
    'open-dm7',
    'Dm7',
    'Sevenths & color',
    ['x', 'x', 0, 2, 1, 1],
    'D',
    'Barre the highest two strings at fret 1.',
  ),
  entry(
    'open-cmaj7',
    'Cmaj7',
    'Sevenths & color',
    ['x', 3, 2, 0, 0, 0],
    'C',
    'Let the open B ring for a major seventh.',
  ),
  entry(
    'open-amaj7',
    'Amaj7',
    'Sevenths & color',
    ['x', 0, 2, 1, 2, 0],
    'A',
    'G# on the third string gives the major seventh.',
  ),
  entry(
    'open-dmaj7',
    'Dmaj7',
    'Sevenths & color',
    ['x', 'x', 0, 2, 2, 2],
    'D',
    'A compact three-string barre above open D.',
  ),
  entry(
    'open-fmaj7',
    'Fmaj7',
    'Sevenths & color',
    ['x', 'x', 3, 2, 1, 0],
    'F',
    'An accessible F-family shape with an open high E.',
  ),
  entry(
    'open-cadd9',
    'Cadd9',
    'Suspended & added',
    ['x', 3, 2, 0, 3, 3],
    'C',
    'The D adds color while the E keeps the major third.',
  ),
  entry(
    'open-dsus2',
    'Dsus2',
    'Suspended & added',
    ['x', 'x', 0, 2, 3, 0],
    'D',
    'Replace the third of D major with an open E.',
  ),
  entry(
    'open-dsus4',
    'Dsus4',
    'Suspended & added',
    ['x', 'x', 0, 2, 3, 3],
    'D',
    'The high G often resolves down to F# in D major.',
  ),
  entry(
    'open-asus2',
    'Asus2',
    'Suspended & added',
    ['x', 0, 2, 2, 0, 0],
    'A',
    'Open B replaces the third of A major.',
  ),
  entry(
    'open-asus4',
    'Asus4',
    'Suspended & added',
    ['x', 0, 2, 2, 3, 0],
    'A',
    'Move the B-string finger between frets 2 and 3.',
  ),
  entry(
    'open-esus4',
    'Esus4',
    'Suspended & added',
    [0, 2, 2, 2, 0, 0],
    'E',
    'A on the G string replaces the major third.',
  ),
  entry(
    'open-a6',
    'A6',
    'Suspended & added',
    ['x', 0, 2, 2, 2, 2],
    'A',
    'F# adds the sixth. These notes can also describe F#m7/A.',
  ),
  entry('open-am6', 'Am6', 'Suspended & added', ['x', 0, 2, 2, 1, 2], 'A', 'A minor with an added F#.'),
  entry(
    'power-e',
    'E5',
    'Power & jazz',
    [0, 2, 2, 'x', 'x', 'x'],
    'E',
    'Root and fifth only, with the root doubled an octave higher.',
  ),
  entry(
    'power-a',
    'A5',
    'Power & jazz',
    ['x', 0, 2, 2, 'x', 'x'],
    'A',
    'A movable fifth-string power shape.',
  ),
  entry(
    'jazz-b-halfdim',
    'Bm7b5',
    'Power & jazz',
    ['x', 2, 3, 2, 3, 'x'],
    'B',
    'B-D-F-A: a half-diminished seventh.',
  ),
  entry(
    'jazz-b-dim7',
    'Bdim7',
    'Power & jazz',
    ['x', 2, 3, 1, 3, 'x'],
    'B',
    'A symmetrical diminished seventh; several roots are possible.',
  ),
  entry(
    'jazz-e9',
    'E9',
    'Power & jazz',
    [0, 2, 0, 1, 0, 2],
    'E',
    'An open dominant ninth with all five chord tones.',
  ),
  entry(
    'jazz-am9',
    'Am9',
    'Power & jazz',
    ['x', 0, 5, 5, 0, 0],
    'A',
    'A-C-E-G-B: all five tones of A minor ninth.',
  ),
  entry(
    'barre-e-f',
    'F major (E-shape barre)',
    'E-shaped barre chords',
    [1, 3, 3, 2, 1, 1],
    'F',
    'Move the open E major shape up one fret and barre fret 1.',
  ),
  entry(
    'barre-e-g',
    'G major (E-shape barre)',
    'E-shaped barre chords',
    [3, 5, 5, 4, 3, 3],
    'G',
    'The lowest-string root is at fret 3; the shape is movable.',
  ),
  entry(
    'barre-e-fsharpminor',
    'F# minor',
    'E-shaped barre chords',
    [2, 4, 4, 2, 2, 2],
    'F#',
    'Move E minor up two frets and barre fret 2.',
  ),
  entry(
    'barre-e-f7',
    'F7',
    'E-shaped barre chords',
    [1, 3, 1, 2, 1, 1],
    'F',
    'The movable E7 form at fret 1.',
  ),
  entry(
    'barre-e-gm7',
    'Gm7',
    'E-shaped barre chords',
    [3, 5, 3, 3, 3, 3],
    'G',
    'A movable minor seventh with its root on string 6.',
  ),
  entry(
    'barre-a-bm',
    'B minor (A-shape minor barre)',
    'A-shaped barre chords',
    ['x', 2, 4, 4, 3, 2],
    'B',
    'Move the A-minor shape to fret 2; the fifth-string root identifies B.',
  ),
  entry(
    'barre-a-b',
    'B major (A-shape barre)',
    'A-shaped barre chords',
    ['x', 2, 4, 4, 4, 2],
    'B',
    'Barre the second fret and place the A major shape above it.',
  ),
  entry(
    'barre-a-c',
    'C major (A-shape barre)',
    'A-shaped barre chords',
    ['x', 3, 5, 5, 5, 3],
    'C',
    'The fifth-string root at fret 3 identifies this movable A shape.',
  ),
  entry(
    'barre-a-dm',
    'D minor (A-shape barre)',
    'A-shaped barre chords',
    ['x', 5, 7, 7, 6, 5],
    'D',
    'An A-minor shape at fret 5; mute the low E string.',
  ),
  entry(
    'triad-g-b-d',
    'G major triad, second inversion',
    'Triads · G-B-e',
    ['x', 'x', 'x', 7, 8, 7],
    'G',
    'The notes are D-G-B, so the fifth is in the bass of this three-string set.',
  ),
  entry(
    'triad-g-d-g-b',
    'G major triad, first inversion',
    'Triads · G-B-e',
    ['x', 'x', 'x', 4, 3, 3],
    'G',
    'The notes are B-D-G, so the third is in the bass of this three-string set.',
  ),
  entry(
    'triad-c',
    'C major triad, root position',
    'Triads · G-B-e',
    ['x', 'x', 'x', 5, 5, 3],
    'C',
    'The top strings give C-E-G; compare its compact sound with open C.',
  ),
  entry(
    'triad-am',
    'A minor triad, first inversion',
    'Triads · G-B-e',
    ['x', 'x', 'x', 5, 5, 5],
    'A',
    'The notes are C-E-A, so the third is in the bass of this three-string set.',
  ),
  entry(
    'triad-d',
    'D major triad, root position',
    'Triads · G-B-e',
    ['x', 'x', 'x', 7, 7, 5],
    'D',
    'D-F#-A on the highest strings is a bright, movable major shape.',
  ),
  entry(
    'scale-em-pentatonic',
    'E minor pentatonic anchor positions',
    'Scales & keys',
    [0, 3, 0, 2, 0, 3],
    'E',
    'One useful anchor per string for the open-position box; this compact card is not the full pattern.',
  ),
  entry(
    'scale-a-minor',
    'A minor pentatonic anchor positions',
    'Scales & keys',
    [5, 8, 5, 7, 5, 8],
    'A',
    'One useful anchor per string around fret 5; this compact card is not the full pattern.',
  ),
  entry(
    'key-g',
    'G major chord-family anchors',
    'Scales & keys',
    [3, 2, 0, 0, 0, 3],
    'G',
    'Start with G, C, and D shapes: the I-IV-V family in the key of G.',
  ),
]);
export const categories = Object.freeze([...new Set(guitarLibrary.map(({ category }) => category))]);
export const shapesByCategory = (category) => guitarLibrary.filter((item) => item.category === category);
export const findShape = (id) => guitarLibrary.find((item) => item.id === id);
